#!/usr/bin/env python

import os
try:
    from urllib.parse import urlencode
except ImportError:  # python2
    from urllib import urlencode

import gentoolkit.helpers
import gentoolkit.package


paths = set()
for dirpath, dirnames, filenames in os.walk('.'):
    for filename in filenames:
        paths.add(os.path.join(dirpath[1:], filename))
packages = set()
installed_packages = gentoolkit.helpers.get_installed_cpvs()
for package_cpv in installed_packages:
    package = gentoolkit.package.Package(cpv=package_cpv)
    contents = set(package.parsed_contents().keys())
    if paths.intersection(contents):
        packages.add(package)
print('packages:')
for package in sorted(packages):
    licenses = package.environment('LICENSE', fallback=False)
    uri = 'https://packages.gentoo.org/packages/{}'.format(
        package.cp)
    print('  {}'.format(package))
    print('    URI: {}'.format(uri))
    print('    licenses: {}'.format(licenses))
    for upstream in package.metadata.upstream():
        for uri, type in upstream.upstream_remoteids():
            if type == 'cpe':
                print('    security: {} (https://nvd.nist.gov/vuln/search/results?{})'.format(
                    uri,
                    urlencode({
                        'adv_search': 'true',
                        'cpe': uri,
                    })))
